# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e258272a9e99dfdfd75cf209397f49deafc96ec754be0b86ae3d0c1bc6296ee5badc26c6f5e54a0d8fb0613e50c2cf9018c173c798f9272cbfe552cccf032870

test:
  secret_key_base: d2822d10bbcf18602fb6e2544e7cb3051c18a0acf49416ff5ac5ac12b75c651a8b8468e65f7d10df159bb1ac42da4fa6f1ce50477c95ee3e71f2f87b8672543e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
